// Code generated by protoc-gen-go.
// source: message.proto
// DO NOT EDIT!

/*
Package proto is a generated protocol buffer package.

It is generated from these files:
	message.proto

It has these top-level messages:
	Message
	UserCmd
	Snapshot
*/
package proto

import proto1 "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto1.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto1.ProtoPackageIsVersion2 // please upgrade the proto package

type Message struct {
	Type int32  `protobuf:"varint,1,opt,name=type" json:"type,omitempty"`
	Name string `protobuf:"bytes,2,opt,name=name" json:"name,omitempty"`
	Data []byte `protobuf:"bytes,3,opt,name=data,proto3" json:"data,omitempty"`
}

func (m *Message) Reset()                    { *m = Message{} }
func (m *Message) String() string            { return proto1.CompactTextString(m) }
func (*Message) ProtoMessage()               {}
func (*Message) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *Message) GetType() int32 {
	if m != nil {
		return m.Type
	}
	return 0
}

func (m *Message) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Message) GetData() []byte {
	if m != nil {
		return m.Data
	}
	return nil
}

type UserCmd struct {
	Seqid int32 `protobuf:"varint,1,opt,name=seqid" json:"seqid,omitempty"`
	Cmdid int32 `protobuf:"varint,2,opt,name=cmdid" json:"cmdid,omitempty"`
}

func (m *UserCmd) Reset()                    { *m = UserCmd{} }
func (m *UserCmd) String() string            { return proto1.CompactTextString(m) }
func (*UserCmd) ProtoMessage()               {}
func (*UserCmd) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *UserCmd) GetSeqid() int32 {
	if m != nil {
		return m.Seqid
	}
	return 0
}

func (m *UserCmd) GetCmdid() int32 {
	if m != nil {
		return m.Cmdid
	}
	return 0
}

type Snapshot struct {
	X int32 `protobuf:"varint,1,opt,name=x" json:"x,omitempty"`
	Y int32 `protobuf:"varint,2,opt,name=y" json:"y,omitempty"`
	D int32 `protobuf:"varint,3,opt,name=d" json:"d,omitempty"`
	V int32 `protobuf:"varint,4,opt,name=v" json:"v,omitempty"`
}

func (m *Snapshot) Reset()                    { *m = Snapshot{} }
func (m *Snapshot) String() string            { return proto1.CompactTextString(m) }
func (*Snapshot) ProtoMessage()               {}
func (*Snapshot) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

func (m *Snapshot) GetX() int32 {
	if m != nil {
		return m.X
	}
	return 0
}

func (m *Snapshot) GetY() int32 {
	if m != nil {
		return m.Y
	}
	return 0
}

func (m *Snapshot) GetD() int32 {
	if m != nil {
		return m.D
	}
	return 0
}

func (m *Snapshot) GetV() int32 {
	if m != nil {
		return m.V
	}
	return 0
}

func init() {
	proto1.RegisterType((*Message)(nil), "proto.Message")
	proto1.RegisterType((*UserCmd)(nil), "proto.UserCmd")
	proto1.RegisterType((*Snapshot)(nil), "proto.Snapshot")
}

func init() { proto1.RegisterFile("message.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 178 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x09, 0x6e, 0x88, 0x02, 0xff, 0x2c, 0x8f, 0xb1, 0x0e, 0x82, 0x30,
	0x10, 0x86, 0x73, 0x4a, 0x45, 0x2f, 0xb8, 0x34, 0x0e, 0x1d, 0x09, 0x13, 0x93, 0x8b, 0xf1, 0x05,
	0x34, 0x8e, 0x2e, 0x35, 0x3e, 0x40, 0xf5, 0x1a, 0x65, 0x28, 0x20, 0x6d, 0x08, 0xbc, 0xbd, 0xe9,
	0x95, 0xa9, 0xff, 0xf7, 0xa5, 0xf7, 0x5f, 0x0e, 0xf7, 0xce, 0x7a, 0x6f, 0x3e, 0xf6, 0xd8, 0x0f,
	0x5d, 0xe8, 0xa4, 0xe0, 0xa7, 0xba, 0x61, 0x7e, 0x4f, 0x5e, 0x4a, 0xcc, 0xc2, 0xdc, 0x5b, 0x05,
	0x25, 0xd4, 0x42, 0x73, 0x8e, 0xae, 0x35, 0xce, 0xaa, 0x55, 0x09, 0xf5, 0x4e, 0x73, 0x8e, 0x8e,
	0x4c, 0x30, 0x6a, 0x5d, 0x42, 0x5d, 0x68, 0xce, 0xd5, 0x19, 0xf3, 0xa7, 0xb7, 0xc3, 0xd5, 0x91,
	0x3c, 0xa0, 0xf0, 0xf6, 0xd7, 0xd0, 0xd2, 0x93, 0x20, 0xda, 0xb7, 0xa3, 0x86, 0xb8, 0x49, 0xe8,
	0x04, 0xd5, 0x05, 0xb7, 0x8f, 0xd6, 0xf4, 0xfe, 0xdb, 0x05, 0x59, 0x20, 0x4c, 0xcb, 0x0c, 0x4c,
	0x91, 0xe6, 0xe5, 0x2f, 0xcc, 0x91, 0x88, 0xf7, 0x09, 0x0d, 0x14, 0x69, 0x54, 0x59, 0xa2, 0xf1,
	0xb5, 0xe1, 0x43, 0x4e, 0xff, 0x00, 0x00, 0x00, 0xff, 0xff, 0x44, 0x69, 0x24, 0x47, 0xe0, 0x00,
	0x00, 0x00,
}
